### ISSUE TITLE
A process for setting up Kubernetes environment for use with Galaxy Helm chart

### ISSUE THREAD

**Issue by almahmoud** [CloudVE/galaxy-helm#47]
Following a conversation with @eschen42 at GCC 2019, it'd be nice to create a recipe for (re)creating a  Kubernetes environment that can be used for deploying Galaxy. Here is an outline of the procedure we used to create VMs for the GCC training and below is a list of tasks that should generalize the approach for others of use.

## Instance launch procedure used at GCC
1. Start [CloudLaunch](https://github.com/galaxyproject/cloudlaunch) locally, with the edit in `configurers.py` to point to a local clone of the custom [ansible-cloudman2 repo](https://github.com/CloudVE/ansible-cloudman2) with `GIST_ID` and `GIST_TOKEN` env vars defined in `playbook.yml` (to obtain these, create a GitHub gist and an API token; the gist is used to pass the Rancher access info from the remote so that `kubectl` and `helm` commands can be setup on it later via `k8s_playbook.yml` ).
2. Run [`launch_many.sh` script](https://gist.github.com/afgane/8748cad926e4a6ddceb8f92abfb0efa2) to create some instances. Note the `"cm_skip_cloudman": "Yes"` key in the app definition. This will kick off [`cloudman-boot` container](https://github.com/CloudVE/cloudman-boot) on the target host. This container will setup Kubernetes using Rancher.
3. Once the `cloudman-boot` container has run to completion it will update the gist with the Rancher info. Grab that info and put it into an `inventory` file.
4. Run `ansible-playbook -i inventory k8s_playbook.yml` from the ansible-cloudman2 repo to install and configure `kubectl` and `helm` commands, along with system user access. Instance IPs and passwords will be in the `keys` directory.

## Tasks to generalize the launch procedure
- [ ] Update ansible-boot playbook & container to create a suitable/configurable storage class
- [ ] Mount the host home dir into cloudman-boot container and copy `.kube/config` to the host. This will allow the entire push-to-gist process to be removed.
- [ ] Add documentation (tutorial?) on how to setup this environment
- [ ] Add an option in CloudLaunch to launch this environment
- [ ] Update CloudLaunch instance at https://launch.usegalaxy.org/

Also pinging @eslerm as Arthur mentioned you might be interested in helping a bit with this to speed it up.
